### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by kilianyp** [janEbert/rldurak#1]
Hi, 
on what hardware were those experiments run?

Thanks

**Comment by janEbert** [comment]
Hey,

This was run only on CPUs on xUbuntu and Windows machines. All of the CPUs were different, some of which were older and did not support AVX2. Otherwise, all available SIMD instructions were used by compiling TensorFlow for each CPU (at the time, TensorFlow was not shipped with natively compiled SIMD instructions).

Thanks for the interest in the project. This was a quickly- and poorly-coded bachelor's thesis which could use a lot of improvement and refactoring (please don't look at the main function). Actually, the whole thing should probably be written from scratch which I hope to do at some point in the future.

If looking at the code does not scare you away (it should) and you are still interested though, I am happy to help or answer any questions.

Cheers!
